//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemistShop.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.IO;
    public partial class Medicines
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int MedicineId { get; set; }
        public int MedicineManufacturerId { get; set; }
        public string MedicineName { get; set; }
        public int MedicineCost { get; set; }
        public int MedicineDiscount { get; set; }
        public double MedicineRank { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime MedicineDateManufacturing { get; set; }
        public int MedicineExpirationDate { get; set; }

        public string ProductPhotoPath
        {
            get
            {
                {
                    string temp = App.pathExe + @"\Photos\" + this.MedicineName  + ".jpg";
                    if (!File.Exists(temp))
                    {
                        temp = @"\Resources\Pictures.png";
                    }
                    return temp;
                }
            }
        }

        public virtual Category Category { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
    }
}
